// <auto-generated />
using System;
using GymManagement.Domain.Models.Presistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GymManagement.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180903181058_AddTableSample")]
    partial class AddTableSample
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview1-35029")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GymManagement.Domain.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(250);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Mobile")
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("GymManagement.Domain.Models.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PersonId");

                    b.Property<string>("SampleValue");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("GymManagement.Domain.Models.Member", b =>
                {
                    b.HasBaseType("GymManagement.Domain.Models.Person");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500);

                    b.Property<DateTime>("JoiningDate");

                    b.Property<DateTime?>("RessignDate");

                    b.Property<int>("Status");

                    b.HasDiscriminator().HasValue("Member");
                });

            modelBuilder.Entity("GymManagement.Domain.Models.Sample", b =>
                {
                    b.HasOne("GymManagement.Domain.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });
#pragma warning restore 612, 618
        }
    }
}
